# Generated by Django 4.0.5 on 2022-06-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
