# Generated by Django 4.0.5 on 2022-06-29 00:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post_datetim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_to),
        ),
    ]
